name: release

on: workflow_dispatch

jobs:

  test:

    name: Run unit tests using tox.

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest tox tox-gh-actions

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with tox
      run: |
        tox

  release:

    name: Upload to PyPI

    if: ${{ (contains(github.ref, 'refs/tags/v') && contains(github.ref, '-dev')) || (github.event_name == 'workflow_dispatch') }}

    runs-on: ubuntu-latest

    needs: test

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pypa/build
      run: |
        python -m pip install build --user

    - name: Build a binary wheel and a source tarball
      run: |
        python -m build --sdist --wheel --outdir dist/ .

    - uses: pypa/gh-action-pypi-publish@master
      name: Upload to PyPI.
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
